### ISSUE TITLE
Replace kmac128 from pyXKCP with pycryptodome

### ISSUE THREAD

**Issue by m-temp** [lowRISC/ot-sca#102]
In https://github.com/lowRISC/ot-sca/pull/54 we added support for KMAC using pyXKCP, which uses some vendor c-sources. We did that, because at this point in time there was no good python kmac implementation available.
However, this adds some c-sources and some cffi scripting.

In the meantime, [kmac128](https://pycryptodome.readthedocs.io/en/latest/src/hash/kmac128.html) and  [kmac256](https://pycryptodome.readthedocs.io/en/latest/src/hash/kmac256.html) were added to [pycryptodome v3.12.0](https://pycryptodome.readthedocs.io/en/v3.12.0/src/changelog.html)

Do we want to streamline our python flow? This has of course a very low priority, but could be a good first issue for some else.

**Comment by vogelpi** [comment]
Hey @m-temp ,
that sounds like a good idea to me. As you say it has a low priority but I think it would be worth to remove the C dependency.
