### ISSUE TITLE
[ecdsa] Don't reset target between traces

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ot-sca#105]
It seems the target is currently reset between capturing different traces or trace segments which leads to very low performance as the binary needs to be transferred over SPI for every segment. We should look into changing the capture setup to not require a reset of the target between segments.

**Comment by m-temp** [comment]
@bilgiday I think this is resolved now, isn't it?

**Comment by bilgiday** [comment]
Yes, it is solved :)

In our OTBN-related capture functions, we were previously using `reset_firmware=True` to reset the target between the traces. Now, we are using `reset_firmware=False` to prevent the reset ([example](https://github.com/lowRISC/ot-sca/blob/11d590f8517effa97275c0f5b0ba655e6ca7edd8/cw/capture.py#L1027)). 

The only task remaining is to completely remove the `reset_firmware` variable. I can do it through a new PR if it makes sense to you.
