### ISSUE TITLE
[ecdsa] Implement golden model

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ot-sca#108]
Similar to AES, KMAC and SHA3 we should have a golden model running in parallel with the target to verify the produced signature on the host side.

**Comment by m-temp** [comment]
From our meeting: This might be a complete model, but more likely to start with some smaller subroutines
For more details see https://docs.google.com/document/d/1sZjASiUji_IT-t9jEFlK-kGc_Gw3mGfubNvpkM_IQT4

**Comment by vogelpi** [comment]
@vrozic @nasahlpa and I have discussed this and concluded that this is not really needed anymore. The issue is from a time when we had a pretty different understanding of how OTBN captures would work.
