### ISSUE TITLE
add doc for sha3 capture and tvla

### ISSUE THREAD

**Issue by m-temp** [lowRISC/ot-sca#112]
@y-srini  mentioned in the ot-sca meeting that some doc regarding sha3 capture and tvla would be helpful.
I'll push a PR soon, but want to address https://github.com/lowRISC/ot-sca/issues/111 first.

**Comment by y-srini** [comment]
@m-temp: 
In the SHA3 batch mode section, the capture parameter should be updated to "sha3-fvsr-data-batch"

./capture.py --cfg-file capture_sha3_cw310.yaml capture **sha3-fvsr-data-batch** --num-traces 100 --plot-traces 10
