### ISSUE TITLE
[objs] update ECC384 binaries

### ISSUE THREAD

**Issue by vrozic** [lowRISC/ot-sca#149]
OT [PR 19380](https://github.com/lowRISC/opentitan/pull/19380) updated `ecc384_serial.c` and `p384_ecdsa_sca.s` to enable trace capturing with the latest setup.

Binaries should be updated.

**Comment by vogelpi** [comment]
Hey @vrozic , @bilgiday, @wettermo ,
I've updated lowRISC/OpenTitan#19380 and intend to merge it once CI passes again. Do you maybe want to try it out again on the board?

**Comment by vrozic** [comment]
#204 Updates this binary and should close this issue.
