### ISSUE TITLE
[ci] Automatic comparison of traces

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/ot-sca#176]
Currently, traces generated in the CI need to be manually inspected. Ideally, an automated comparison of generated traces to a golden model is conducted.

**Comment by nasahlpa** [comment]
Yes, I agree. We (@vogelpi @vrozic) were thinking that this could be useful to test upcoming changes in the SCA infrastructure. For this purpose, I think it might be an option to generate traces with a fixed OT version and compare to golden traces.

**Comment by johannheyszl** [comment]
makes sense :)
