### ISSUE TITLE
[capture] Specify offset in clk cycles

### ISSUE THREAD

**Issue by vrozic** [lowRISC/ot-sca#177]
At the moment, measurement offset in capture configuration files is specified in samples.
It probably makes more sense to use clk cycles of the target as a unit of measurement.

**Comment by vogelpi** [comment]
@vrozic is working on this and we've briefly discussed this today. Even if for the time being the computation of the offsets and number of samples / window size happens in / close to the scope code this would be okay. We can refine this later.

Ideally we have a first working version for this soon. We need this to re-enable captures with latest bitstreams (use different target clock frequencies on the CW310). My goal is to work on this in the second half of this week.

**Comment by vogelpi** [comment]
Update: we merged PR #203 which implements the corresponding changes in the CW-based setup. What's left to do is to align the WaveRunner implementation.

**Comment by vogelpi** [comment]
I am thus un-assigning myself and @vrozic and instead assign @johannheyszl who might be able to take care of the WaveRunner part when returning to work.

**Comment by johannheyszl** [comment]
has been addressed in #242
