### ISSUE TITLE
[capture] Change device-side trigger; remove FPGA-specific HW modification

### ISSUE THREAD

**Issue by johannheyszl** [lowRISC/ot-sca#198]
Currently, the device SW sets the trigger HI/LO and in HW this is AND-ed with the AES !IDLE signal. This generates tight trigger HI/LO envelopes around the AES computation. For the longer term, we need to change this behaviour and have the trigger purely controlled by SW. TODO: Change this and test.

**Comment by vogelpi** [comment]
I have been working on this, a first PR is here lowRISC/OpenTitan#20248.

**Comment by johannheyszl** [comment]
@vogelpi thanks is this good to close?

**Comment by vogelpi** [comment]
Yep, that's done. We do have the option to switch to the lower precision trigger.
