### ISSUE TITLE
[capture] Simple script for OTBN

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/ot-sca#216]
As the old [capture.py](https://github.com/lowRISC/ot-sca/blob/master/cw/capture.py) file is not working anymore due to the repo restructure, we need to implement the OTBN capture.
Please use [capture_aes.py](https://github.com/lowRISC/ot-sca/blob/master/capture/capture_aes.py) as a boilerplate.

**Comment by m-temp** [comment]
Can we close this issue, or is there anything missing?

**Comment by wettermo** [comment]
The PR is successfully merged and there shouldn't be anything missing.
We can close this issue.
