### ISSUE TITLE
[capture] Simple script for KMAC

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/ot-sca#217]
As the old [capture.py](https://github.com/lowRISC/ot-sca/blob/master/cw/capture.py) file is not working anymore due to the repo restructure, we need to implement the KMAC capture.
Please use [capture_aes.py](https://github.com/lowRISC/ot-sca/blob/master/capture/capture_aes.py) as a boilerplate.

**Comment by m-temp** [comment]
I'm working on this. However, it will take some time to test it in the office.

**Comment by m-temp** [comment]
Technically KMAC (and SHA3) doesn't have a ciphertext, but a tag. In the past, we used the term ciphertext (and the associated fields) to refer to the Tag/Hash. Should we keep this naming?

**Comment by nasahlpa** [comment]
I guess it would make sense to use the correct naming, .e.g, tag. I think this increases the readability of the code.

However, the new trace library currently only supports the ciphertext/plaintext/key field. It should be fairly easy to add new fields.

**Comment by m-temp** [comment]
There's a first draft (not PR yet) at 8d40089
Currently there are two main issues:
 - still the old variable names (I'd fix that in a second commit)
 - Previously an AES instance was used to generate the next key/plaintext in **non batch** fvsr mode. However in batch mode the internal prng was used. I think this should be aligned in either case

**Comment by m-temp** [comment]
I've changed the priority, as the main task is done now. The new kmac capture script has now the same functionality as the old one. However I leave this issue open, as there are still some points to be discussed. See above.

Feel free to close this issue and track the remaining tasks in a different issue
