### ISSUE TITLE
[capture] USB and Unknown ChipWhisperer errors

### ISSUE THREAD

**Issue by vrozic** [lowRISC/ot-sca#225]
After the latest changes in capture setups, we are experiencing problems when capturing using ChipWhisperer Husky.
Currently, I am not sure what is causing the problem, but these are the symptoms: 

1. The first capture after powering-up Husky creates a permanent problem with USB communication. This happens during `scope.capture_and_transfer_waves()` functions, and results in the USB error `raiseUSBError raise__STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value) usb1.USBErrorIO: LIBUSB_ERROR_IO [-1]`
2. In every following capture attempt, the USB communication is not working, so Husky is unable to identify itself. This results in the following error: `ValueError: Unknown ChipWhisperer:`

I will investigate this further to find a permanent fix, but a temporary workaround is to:

1. Power-up Husky
2. Run one of the captures from the earlier versions of the repository
3. Run any captures from the current repository. Everything should work until the next power-down.

Huskies in the CI setup are always powered-on, so the CI should be stable for now.

**Comment by colinoflynn** [comment]
Tagging @alex-dewar - he might be able to comment on this too, we had some changes in USB connection logic to fix a problem on one platform. Not sure if you're pulling in those changes, but even if not might have more insight into what could cause that issue on connect.

**Comment by vrozic** [comment]
Thanks @colinoflynn ,
We are using a very old version of CW
`https://github.com/newaetech/chipwhisperer-historical.git@3eace1719daf43d4f0965c1790c2c8a9e8b2f690#egg=chipwhisperer`

We've recently been making a lot of changes in the capture scripts, so it's possible that we've awoken some ancient bug.

**Comment by m-temp** [comment]
same happend here, so it's not board/PC/cable/setup specific.

**Comment by alex-dewar** [comment]
Had connection issues on that commit (maybe related to https://github.com/newaetech/chipwhisperer/pull/466?), but everything seems to be working okay on the latest commit. I think the chipwhisperer version used in this repo changed recently, so it could be related to that.
