### ISSUE TITLE
[capture] FVSR non-batch not working

### ISSUE THREAD

**Issue by nasahlpa** [lowRISC/ot-sca#233]
Before the changes with the data generator (8[9642597bbf88394c734e3d755beda689b804eed](https://github.com/lowRISC/ot-sca/commit/89642597bbf88394c734e3d755beda689b804eed) vs [c67ec6327ca31e90c0ab2e332a81d14b6cdd3b9a](https://github.com/lowRISC/ot-sca/commit/c67ec6327ca31e90c0ab2e332a81d14b6cdd3b9a)) the non batch FVSR AES capture worked.
Now, there is a mismatch on the retrieved ciphertext. As I am not sure whether the error is on the host or device side (aes simpleserial program), could you please take a look @vrozic ?

**Comment by vrozic** [comment]
PR #227 fixes this.
All captures should work correctly after it's merged.

**Comment by nasahlpa** [comment]
Ah amazing, thanks! Was not aware that this is related.
