### ISSUE TITLE
[capture] CW databases broken

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ot-sca#274]
Currently, our tvla script seems to only extract the first 20k traces of a CW database. I have several databases holding 2M and 10M AES traces but only the first 20k traces are effectively read out.

Does anyone know why this is the case and how to fix it? @nasahlpa @vrozic ?

**Comment by johannheyszl** [comment]
oh, back in October/November when I last used the script, it reported on stdout that it would use larger numbers. Does it report 20k on stdout now?

**Comment by nasahlpa** [comment]
I am not aware of such a limit - could you please provide me with the DB file and I try to reproduce & fix it.

**Comment by vogelpi** [comment]
Hm, this is strange. I've now switched to an old version and it still just takes the first 20k traces. I am wondering if maybe the database is actually broken.

**Comment by vogelpi** [comment]
A quick investigation of the generated CW project files reveals that all but the last two 10k segments are "disabled". When storing the segments or at the very end of the capture, we have to enable them. This seems to have gone wrong when reworking the capture setup. I'll adjusted the title accordingly and will file a PR.
