### ISSUE TITLE
React to changes in spi and spiflash

### ISSUE THREAD

**Issue by alphan** [lowRISC/ot-sca#34]
`SPIFLASH_RAW_BUFFER_SIZE ` (sw/device/boot_rom/spiflash_frame.h) increased from `1024` to `2048` lowRISC/opentitan#5068.

I took a quick look and unless I missed something this shouldn't break our workflow but we should increase the frame size for the sake of efficiency.

@vogelpi @moidx fyi.

**Comment by vogelpi** [comment]
Thanks @alphan for creating the issue. I was also wondering: are the current capture scripts still compatible with the latest changes you did for higher capture rate, or do we need adjustments for these, too?

**Comment by alphan** [comment]
Yes, we need updates, I'll create a PR for that soon.

**Comment by alphan** [comment]
Should be closed after #40 lands.
