### ISSUE TITLE
board variable should be an enum

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ot-sca#49]
The variable to distinguish the board (CW310 vs. CW305) is currently just a string, but this should be an enum. See [comment](https://github.com/lowRISC/ot-sca/pull/47#discussion_r681803021).

**Comment by vrozic** [comment]
There have been many changes in the repository since this issue was opened.
We are now distinguishing between boards in `device.py` using the name of the bitstream file, and no longer using the `board` variable.
I am therefore closing this issue.
